trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo Executing build steps...
      displayName: 'Build Step'
    # Adicione aqui seus comandos de construção do projeto

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo Executing test steps...
      displayName: 'Test Step'
    # Adicione aqui seus comandos de teste do projeto

# Adicione mais estágios conforme necessário para implantação, notificações, etc.
